pipeline {
    agent any    
    parameters {
         string( defaultValue: "None", description: "Custom deployment name", name: "CustomDeployment" )
         choice( choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "Select AZ", name: "appZone")
         booleanParam( defaultValue: false, description: "Confirm Deployment", name: "deployConfirm" )
    }    

    stages {
        stage("Test") {
            steps {
            echo "Testing..."
            echo "Custom deployment is set to ${params.CustomDeployment}"
            dir("simple-java-maven-app") {
                sleep(10)        
            }
            echo "Done."
            }
        }
        stage("Deploy") {
            steps {
            script {
                if(params.deployConfirm) {
                    echo "Deploying to ${params.appZone}"
                    echo "Done."
                } else {
                    echo "Deployment Skipped."
                }
                }
            }           
        }
        stage("Verify") {
            steps {
            echo "Deployment verified."
            }
        }
    }
}
